---
- name: Configure OPS445 VM
  hosts: spaudel11
  become: yes
  vars:
    seneca_id: spaudel11
    ssh_pub_key: "{{ lookup('file', '/home/spaudel11/.ssh/id_rsa.pub') }}"
    lab_directories:
      - lab1
      - lab2
      - lab3
      - lab4
      - lab5
      - lab6
      - lab7
      - lab8
      - lab9

  tasks:
    - name: update Apache
      yum:
        name: httpd
        state: latest

    - name: install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: remove 'tree' package
      yum:
        name: tree
        state: absent

    - name: set hostname
      hostname:
        name: "{{ seneca_id }}"

    - name: create a new user with sudo access
      user:
        name: "{{ seneca_id }}"
        groups: wheel
        state: present
        password: "{{ 'P@ssw0rd' | password_hash('sha512') }}"

    - name: ensure .ssh directory exists
      file:
        path: "/home/{{ seneca_id }}/.ssh"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0700'

    - name: add SSH key
      shell: "echo '{{ ssh_pub_key }}' >> /home/{{ seneca_id }}/.ssh/authorized_keys"
      args:
        creates: "/home/{{ seneca_id }}/.ssh/authorized_keys"
      become_user: "{{ seneca_id }}"

    - name: set permissions on authorized_keys
      file:
        path: "/home/{{ seneca_id }}/.ssh/authorized_keys"
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0600'

    - name: setup directory structure for labs
      file:
        path: "/home/{{ seneca_id }}/ops445/lab{{ item }}"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0755'
      loop: "{{ range(1, 10) | list }}"
